import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar/Navbar'
import './globals.css'
import Provider from './components/Provider/SessionProvider';
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session =  await getServerSession()
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider session={session}>
        <Navbar />
        {children}
        </Provider>
        </body>
    </html>
  )
}
